#!/usr/bin/env bash

runIfExists() {
    FILE="$1"
    if [ -f "$FILE" ]; then
        "$FILE"
    fi
}

deleteIfExists() {
    FILE="$1"
    if [ -f "$FILE" ]; then
        rm "$FILE"
    fi
}

runIfExists /usr/bin/azkaban-solo-shutdown
deleteIfExists /var/run/azkaban-solo-server/currentpid
deleteIfExists /var/log/azkaban-solo-server/output.log
deleteIfExists /var/log/azkaban-solo-server/error.log

